### ISSUE TITLE
ROT ja Unicode

### ISSUE THREAD

**Issue by Karvaporsas** [akuankka128/js_libs#1]
Hei,

Asiallista koodia sinulla täällä. Osaisitko kuvailla 

a) millä tavalla funktio käyttäytyy kun sille annetaan merkkejä jotka eivät ole mukana funktion veriossa, esim ääkkösiä, ja 

b) mitä muutoksia tekisit jotta funktio toimisi jollain muullakin kuin ASCII-merkistöllä?

**Comment by akuankka128** [comment]
Do you mind if I speak in English? I feel like it's easier for me, and I know more terms related to coding in it.

Well, anyways,
a. it will replace the "unknown" characters with the `(-1 + rot) % 26`-th letter from the alphabet (in the case of rot13, the 12th, which correlates to the letter M)
b. my brain can't think of really anything else other than extending the character set

**Comment by Karvaporsas** [comment]
Yeah, English might indeed be a good language here. :)

How would the code look if you created a class called "Rot", and the class could be initialized with given custom character sets and the amount of rotation on creation, and the class had two methods, encode and decode, that did the same work that your method does at the moment?

**Comment by akuankka128** [comment]
It would look...
Much better!

![image](https://user-images.githubusercontent.com/30865373/82828928-cab22680-9eba-11ea-89c7-88eab63e7332.png)

- Cleaner code
- Easier to understand
- Intuitive

**Comment by Karvaporsas** [comment]
That's a clean and elegant solution to the problem.
